# Generated by Django 6.0.6 on 2026-06-30 11:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget_npr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency_preference', models.CharField(default='NPR', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('destination', 'Destination Visit'), ('guide', 'Guide'), ('package', 'Tour Package'), ('custom', 'Custom Activity'), ('accommodation', 'Accommodation'), ('transport', 'Transport')], max_length=20)),
                ('custom_title', models.CharField(blank=True, max_length=255)),
                ('custom_description', models.TextField(blank=True)),
                ('day_number', models.PositiveSmallIntegerField(default=1)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost_npr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.guideregistry')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bookings.tourpackage')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.trekkingroute')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workspace.travelworkspace')),
            ],
            options={
                'ordering': ['day_number', 'display_order'],
                'indexes': [models.Index(fields=['workspace', 'day_number', 'display_order'], name='workspace_w_workspa_0342eb_idx')],
            },
        ),
    ]
