# Generated by Django 6.0.6 on 2026-08-20 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_guiderequest_guideoffer_traveloffering_and_more'),
        ('catalog', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_exactly_one_target',
        ),
        migrations.AddField(
            model_name='review',
            name='guide_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_account_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guide__isnull', False), ('guide_account__isnull', True), ('route__isnull', True)), models.Q(('guide__isnull', True), ('guide_account__isnull', False), ('route__isnull', True)), models.Q(('guide__isnull', True), ('guide_account__isnull', True), ('route__isnull', False)), _connector='OR'), name='review_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('guide_account__isnull', False)), fields=('author', 'guide_account'), name='uniq_review_author_guide_account'),
        ),
    ]
