# Generated by Django 6.0.6 on 2026-08-20 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_preferences_for_existing_users(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    UserPreferences = apps.get_model('authentication', 'UserPreferences')
    UserPreferences.objects.bulk_create(
        [UserPreferences(user_id=user_id) for user_id in User.objects.values_list('id', flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='availability',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('AVAILABLE', 'Available'), ('BUSY', 'Busy')], db_index=True, default='OFFLINE', max_length=16),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='availability_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='daily_rate_npr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='hourly_rate_npr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='en', max_length=16)),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('theme', models.CharField(choices=[('SYSTEM', 'System'), ('LIGHT', 'Light'), ('DARK', 'Dark')], default='SYSTEM', max_length=8)),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('booking_notifications', models.BooleanField(default=True)),
                ('festival_notifications', models.BooleanField(default=True)),
                ('safety_notifications', models.BooleanField(default=True)),
                ('profile_is_private', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_preferences_for_existing_users, migrations.RunPython.noop),
    ]
