# Generated by Django 6.0.6 on 2026-08-20 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=16, unique=True)),
                ('pickup_name', models.CharField(max_length=180)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_name', models.CharField(max_length=180)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('duration_hours', models.PositiveSmallIntegerField(default=4)),
                ('group_size', models.PositiveSmallIntegerField(default=1)),
                ('requirements', models.TextField(blank=True)),
                ('proposed_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommended_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching for guides'), ('OFFERED', 'Offers received'), ('ACCEPTED', 'Guide accepted'), ('EN_ROUTE', 'Guide en route'), ('ARRIVED', 'Guide arrived'), ('ACTIVE', 'Trip active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='SEARCHING', max_length=16)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('accepted_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_guide_requests', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_guide_requests', to=settings.AUTH_USER_MODEL)),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eta_minutes', models.PositiveSmallIntegerField(default=15)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=12)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_offers', to=settings.AUTH_USER_MODEL)),
                ('guide_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='bookings.guiderequest')),
            ],
            options={
                'ordering': ['offered_fare', 'eta_minutes'],
            },
        ),
        migrations.CreateModel(
            name='TravelOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('FLIGHT', 'Flight'), ('BUS', 'Bus')], db_index=True, max_length=8)),
                ('provider_name', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, db_index=True, max_length=140)),
                ('origin', models.CharField(blank=True, db_index=True, max_length=140)),
                ('destination', models.CharField(blank=True, db_index=True, max_length=140)),
                ('departure_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('available_units', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['unit_price', 'departure_at'],
                'indexes': [models.Index(fields=['service_type', 'origin', 'destination'], name='bookings_tr_service_69b6eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TravelServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=16, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('travellers', models.PositiveSmallIntegerField(default=1)),
                ('units', models.PositiveSmallIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('status', models.CharField(choices=[('PAYMENT_PENDING', 'Payment pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PAYMENT_PENDING', max_length=20)),
                ('passenger_details', models.JSONField(blank=True, default=list)),
                ('special_requests', models.TextField(blank=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.traveloffering')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_service_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guiderequest',
            index=models.Index(fields=['status', 'scheduled_at'], name='bookings_gu_status_59000d_idx'),
        ),
        migrations.AddConstraint(
            model_name='guideoffer',
            constraint=models.UniqueConstraint(fields=('guide_request', 'guide'), name='unique_offer_per_guide_request'),
        ),
    ]
