# Generated by Django 6.0.6 on 2026-08-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_checkout_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=16),
        ),
    ]
